### ISSUE TITLE
Fresh clone `make test` complains of missing HSpec and QuickCheck

### ISSUE THREAD

**Issue by coltfred** [adomokos/haskell_katas#1]
All the files fail to build because it doesn't know how to find the dependencies. Did you mean to put this in a stack project so the dependencies are all in place? 

Some error examples.
```
test/42_maybe_monoids.hs:1:1: error:
    Failed to load interface for ‘Test.Hspec’
    Use -v to see a list of the files searched for.

test/42_maybe_monoids.hs:2:1: error:
    Failed to load interface for ‘Test.QuickCheck’
    Use -v to see a list of the files searched for.

test/02_list_comprehensions.hs:1:1: error:
    Failed to load interface for ‘Test.Hspec’
    Use -v to see a list of the files searched for.

test/02_list_comprehensions.hs:2:1: error:
    Failed to load interface for ‘Test.QuickCheck’
    Use -v to see a list of the files searched for.

```

**Comment by adomokos** [comment]
Good point. I installed HSpec globally, that way I can run the tests without compilation via `runhaskell`. That resembles of an interpreted language environment.

I'll look into how to set up that environment.

**Comment by cjwebb** [comment]
I had some success at installing Hspec with Stack by adding a cabal file:

```
name:                katas
version:             0.1.0.0
cabal-version:       >=1.10

test-suite katas-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Spec.hs
  build-depends:       base
                     , hspec
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

```

And an almost empty stack.yaml:

```
resolver: lts-8.23

packages:
- '.'
extra-deps:

flags: {}

extra-package-dbs: []
```

And then changing `make test` to run this:

```
@$(foreach file,$(FILES), stack runghc $(file);)
```

It runs the tests, but all at once. I'm not sure this is the expected behaviour, but hopefully that will help at least a little!

I'm still not great at Haskell, so looking forward to working through these exercises!

**Comment by adomokos** [comment]
@cjwebb - would you mind sending your changes in a PR? I'd like to test out your solution. Thanks!

**Comment by cjwebb** [comment]
I can do, when it works! I tried reverting and reapplying all my changes, and it doesn't work 😢 
I think I must have installed HSpec globally with Stack.
I'll post again if I can get a reproducible change working, but as I said, I'm still not great at Haskell!

**Comment by adomokos** [comment]
I changed the project to use Stack and HSpec. Closing it.
